### ISSUE TITLE
How spell of latest commit message ?

### ISSUE THREAD

**Issue by antonpatsev** [rojopolis/spellcheck-github-actions#101]
Hello! I try use you github action for spell of commit message.
But it don`t spell commit message.
Please add spell of latest commit message. Thanks!

**Comment by jonasbn** [comment]
Hi @antonpatsev 

This GitHub action is aimed at working at repository contents.

I do however have [an experimental implementation](https://github.com/jonasbn/pre-commit-hooks#spellcheck) of an integration of [`pyspelling`](https://github.com/facelessuser/pyspelling), which is also in used by this action. The implementation is for [pre-commit](https://pre-commit.com/) and awesome framework for commit hooks.

I hope the above can help, since I do not have any knowledge of any GitHub actions working on commits as you mention.
