### ISSUE TITLE
Action uses non-standard configuration location

### ISSUE THREAD

**Issue by proffalken** [rojopolis/spellcheck-github-actions#109]
In order to ensure good developer experience, we want to allow developers to run the same commands on their workstations as is run by the CI.

Unfortunately this is not possible with spellcheck-github-actions, as it relies on `.spellcheck.yaml` whereas `pyspellcheck` relies on `.pyspelling.yaml`.

This means that we either cater to the github action and tell our developers to run `pyspelling` with the `-c` flag set, or we have to change the config for the action to explicitly include `.pyspelling.yaml`.

Given that the `PySpelling` default config location is `.pyspelling.yaml` it would be great if this file was also added to the list of default configuration files.

If people are open to this change, I'm more than happy to create the PR to fix it! :)

**Comment by jonasbn** [comment]
Hi @proffalken 

Thanks for raising the issue, I will evaluate and get back to you.

**Comment by jonasbn** [comment]
As stated in the initial description the default configuration file for **PySpelling** is named: `.pyspelling.yml`.

REF: [PySpelling documentation](https://facelessuser.github.io/pyspelling/#command-line-usage)

**Comment by jonasbn** [comment]
Hi @proffalken 

A PR would be most welcome.

Please be aware, that we might need to take into consideration both variations of YAML suffixes.

- `*.yml`
- `*.yaml`

According to the documentation, `*.yml` is used, but in [the code](https://github.com/facelessuser/pyspelling/blob/670f36b2c0925444b396546c04f5972af6d529a1/pyspelling/util/__init__.py#L169) both are supported if I am not mistaken. 

However since the parameter is feed to `--config`, we might as well accommodate for both, since they are both valid.
