### ISSUE TITLE
Possible to ignore words in magic commands?

### ISSUE THREAD

**Issue by ShawnHymel** [rojopolis/spellcheck-github-actions#153]
We use this action to check our markdown prior to publishing to GitBook. In GitBook, we can embed videos with the following magic command:

```
{% embed url="https://www.youtube.com/watch?v=0Uga3GVXgMw" %}
```

I see that the action can ignore markdown links as per #24 , bit it seems to miss magic commands such as this. I get the following output:

```
Using pyspelling on configuration outlined in >.spellcheck.yaml<
Checking files matching specified outlined in >.spellcheck.yaml<
----------------------------------------------------------------
Misspelled words:
<htmlcontent> edge-impulse-python-sdk/overview.md: html>body>p
--------------------------------------------------------------------------------
GVXgMw
Uga
--------------------------------------------------------------------------------

!!!Spelling check failed!!!
Error: Files in repository contain spelling errors
```

Is there any way to specify ignore strings between characters/strings, for example, between `{%` and `%}`?

**Comment by jonasbn** [comment]
Hi @ShawnHymel 

This is basically just a GitHub Action and Docker image packaging the program PySpelling.

I believe you would have more luck redirecting you inquiry to that repository, since it deals with the configuration and options offered by PySpelling, if there is something that PySpelling offers that this action does not support, I will gladly look into it.

- https://github.com/facelessuser/pyspelling
