### ISSUE TITLE
Failing to build

### ISSUE THREAD

**Issue by albertvolkman** [rojopolis/spellcheck-github-actions#20]
When attempting to run this, I get the following error-
```
/bin/sh: apt-get: not found
```

https://github.com/EsteemedIO/esteemedio.github.io/runs/820756861

**Comment by jonasbn** [comment]
Hello @albertvolkman 

The build you demonstrate is based on: [UnicornGlobal/spellcheck-github-actions](https://github.com/UnicornGlobal/spellcheck-github-actions) and not the action provided by this repository.

You need to report your issue with [UnicornGlobal/spellcheck-github-actions](https://github.com/UnicornGlobal/spellcheck-github-actions), the fork seems to have diverged from this repository and the code bases are no longer compatible.

As you can see on the main page of [UnicornGlobal/spellcheck-github-actions](https://github.com/UnicornGlobal/spellcheck-github-actions)

> This branch is 14 commits ahead, 42 commits behind rojopolis:master. 

I would love to help, but I cannot allocate time to maintain forks, which are not my own -  that said, the output from your action does point to some issues.

Line 4: `Step 1/9 : FROM python:3.7-alpine3.10`
Line: 36: `/bin/sh: apt-get: not found`

To my knowledge `apt-get` is available on Debian and Ubuntu as APT ([resource](https://en.wikipedia.org/wiki/APT_(software))), the package manager for Alpine is called: `apk` ([resource](https://wiki.alpinelinux.org/wiki/Alpine_Linux_package_management))

I hope this helps - if [UnicornGlobal/spellcheck-github-actions](https://github.com/UnicornGlobal/spellcheck-github-actions) is aligned with this repository, I would be able to help you.

**Comment by albertvolkman** [comment]
My apologies! Thank you.

**Comment by albertvolkman** [comment]
I switched it to your branch, and it's now building the image properly, but I'm getting an error about it not loading the pyspelling config-

https://github.com/EsteemedIO/esteemedio.github.io/runs/822528309?

I'm following the default example provided-

https://github.com/EsteemedIO/esteemedio.github.io/blob/master/spellcheck.yaml

**Comment by jonasbn** [comment]
Hi @albertvolkman 

I have added [a PR to your project](https://github.com/EsteemedIO/esteemedio.github.io/pull/24), which addresses the issue you observe.

The issue is that your workflow does not checkout the repository to work on, so I have added that.

I can see this is not clear from the documentation for the action, I will clarify this.

Thanks for your bug report, let me know if you have any more issues.

BTW, [the action works now](https://github.com/EsteemedIO/esteemedio.github.io/pull/24/checks?check_run_id=823620213),  so you have some potential spelling mistakes to attend to or add to a custom dictionary. 

Please consult the documentation and let me know if anything is unclear, so I can correct this part also and assist you.

Take care and stay safe,

@jonasbn
