### ISSUE TITLE
Push image to Docker Hub or GitHub Packages

### ISSUE THREAD

**Issue by tomlankhorst** [rojopolis/spellcheck-github-actions#9]
The image is built on every run. 
The process could be sped up significantly by pushing the Dockerfile to Docker Hub (for automatic building) or GitHub packages and then use it from there. 

Do you consider this an option?

**Comment by jonasbn** [comment]
It is quite slow

**Comment by jonasbn** [comment]
Hi @tomlankhorst 

I have just release 0.4.0 to GitHub Marketplace. Next up is addressing this particular issue.

**Comment by edumco** [comment]
> It is quite slow

The image itself could be improved for performance, build time and download time by:

- Using a smaller image (alpine)

- Using a `.dockerignore` (docker copies all files in the repo even if you don't use)

**Comment by jonasbn** [comment]
Hi @tomlankhorst and @edumco 

I have pushed a "jonasbn/github-action-spellcheck:0.5.0" [to DockerHub](https://hub.docker.com/r/jonasbn/github-action-spellcheck).

Would any of you be interested in reviewing it, the code is available in PR: #12 

I have labelled the Docker image 0.5.0 since I expect it to be a part of the 0.5.0 release of the action, it is however also available as: "jonasbn/github-action-spellcheck:latest".

If do not hear anything I expect to release 0.5.0 to the Marketplace within a few days.

**Comment by jonasbn** [comment]
@edumco please see my comment in PR #12 on Alpine. I am not giving up on _slimming_ down the image even further, but I am not so familiar with Alpine, so it will take some time to get into possibly addressing the issues observed with the XML and XSLT dependencies, which demonstrate issues when building on Alpine.

**Comment by edumco** [comment]
> @edumco please see my comment in PR #12 on Alpine. I am not giving up on _slimming_ down the image even further, but I am not so familiar with Alpine, so it will take some time to get into possibly addressing the issues observed with the XML and XSLT dependencies, which demonstrate issues when building on Alpine.

The suggestions I made dont need to happen all together. Alpine is a little tricky. In some cases makes the dockerfile more complex. I will look the PR :dancers:
